version: '3.8'
services:
  infinitynumerology:
    build:
      context: .
      dockerfile: InfinityNumerology/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: root
      POSTGRES_DB: numerology_user_info
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
